import random

def debut():
    world.write('<?xml version="1.0"?>')
    world.write("\n<sdf version='1.4'>")
    world.write("\n    <world name='default'>")

def ciel_et_soleil(sunrise, clouds, sunset):
    #entre 0 et 24 sunrise
    #entre 0 et 24 clouds
    #entre 0 et 24 sunset
    world.write('\n	<scene>')
    world.write('\n		<sky>')
    sunrise = ('\n			<sunrise>'+str(sunrise)+'</sunrise>')
    world.write(sunrise)
    clouds = ('\n			<clouds>'+str(clouds)+'</clouds>')
    world.write(clouds)
    sunset = ('\n			<sunset>'+str(sunset)+'</sunset>')
    world.write(sunset)
    world.write('\n		</sky>')
    world.write('\n	</scene>')
    world.write('\n	<include>')
    world.write('\n    		<uri>model://sun</uri>')
    world.write('\n		<pose>0.0 0.0 10.0  0 0 0</pose>')
    world.write('\n	</include>')

def sol(size,texture):
    world.write("\n        <model name='ground_plane'>")
    world.write('\n            <static>1</static>')
    world.write("\n            <link name='link'>")
    world.write("\n                <collision name='collision'>")
    world.write('\n                    <geometry>')
    world.write('\n                        <plane>')
    world.write('\n                            <normal>0 0 1</normal>')
    size = '\n                            <size>'+str(size)+' '+str(size)+'</size>'
    world.write(size)
    world.write('\n                        </plane>')
    world.write('\n                    </geometry>')
    world.write('\n                    <surface>')
    world.write('\n                        <friction>')
    world.write('\n                            <ode>')
    world.write('\n                               <mu>100</mu>')
    world.write('\n                               <mu2>50</mu2>')
    world.write('\n                            </ode>')
    world.write('\n                        </friction>')
    world.write('\n                        <bounce/>')
    world.write('\n                        <contact>')
    world.write('\n                            <ode/>')
    world.write('\n                        </contact>')
    world.write('\n                    </surface>')
    world.write('\n                    <max_contacts>10</max_contacts>')
    world.write('\n                </collision>')
    world.write("\n                <visual name='visual'>")
    world.write('\n                    <cast_shadows>0</cast_shadows>')
    world.write('\n                    <geometry>')
    world.write('\n                        <plane>')
    world.write('\n                            <normal>0 0 1</normal>')
    world.write(size)
    world.write('\n                        </plane>')
    world.write('\n                    </geometry>')
    world.write('\n                    <material>')
    world.write('\n                        <script>')
    world.write('\n                           <uri>file://media/materials/scripts/gazebo.material</uri>')
    texture = ('\n                            <name>Gazebo/'+str(texture)+'</name>')
    world.write('\n                            <name>Gazebo/Grass</name>')
    world.write('\n                        </script>')
    world.write('\n                    </material>')
    world.write('\n                </visual>')
    world.write('\n                <velocity_decay>')
    world.write('\n                    <linear>0</linear>')
    world.write('\n                    <angular>0</angular>')
    world.write('\n                </velocity_decay>')
    world.write('\n                <self_collide>0</self_collide>')
    world.write('\n                <kinematic>0</kinematic>')
    world.write('\n                <gravity>1</gravity>')
    world.write('\n            </link>')
    world.write('\n        </model>')

def debut_obsacle(nom):
    name = ("	<model name="+"'"+nom+"'"+">")
    world.write(name)
    world.write('		<static>1</static>')

def create_arbre(number,pos_X,pos_Y):
    #creation du tronc
    nom_tronc = ('\n		<link name="tronc_'+str(number)+'">')
    world.write(nom_tronc)
    pos_tronc = ('\n			<pose>'+str(pos_X)+' '+str(pos_Y)+' 1.0  0 0 0</pose>')
    world.write(pos_tronc)
    world.write('\n			<visual name="visual">')
    world.write('\n				<geometry>')
    world.write('\n					<box>')
    world.write('\n						<size>0.5 0.5 2.0</size>')
    world.write('\n					</box>')
    world.write('\n				</geometry>')
    world.write('\n				<material>')
    world.write('\n					<ambient>0.4 0.3 0.2 1</ambient>')
    world.write('\n					<diffuse>0.3 0.2 0.1 1</diffuse>')
    world.write('\n					<specular>0.1 0.1 0.1 1</specular>')
    world.write('\n					<emissive>0 0 0 0</emissive>')
    world.write('\n					<script>')
    world.write('\n                            			<uri>file://media/materials/scripts/gazebo.material</uri>')
    world.write('\n                            			<name>Gazebo/Red</name>')
    world.write('\n                        		</script>')
    world.write('\n				</material>')
    world.write('\n			</visual>')
    world.write('\n			<collision name="collision">')
    world.write('\n				<geometry>')
    world.write('\n					<box>')
    world.write('\n						<size>0.5 0.5 2.0</size>')
    world.write('\n					</box>')
    world.write('\n				</geometry>')
    world.write('\n			</collision>')
    world.write('\n		</link>')
    #creation du feuillage
    nom_feuillage = ('\n		<link name="feuillage_'+str(number)+'">')
    world.write(nom_feuillage)
    pos_feuillage = ('\n			<pose>'+str(pos_X)+' '+str(pos_Y)+' 2.5.0  0 0 0</pose>')
    world.write(pos_feuillage)
    world.write('\n			<visual name="visual">')
    world.write('\n				<geometry>')
    world.write('\n					<sphere>')
    world.write('\n						<radius>6.0</radius>')
    world.write('\n					</sphere>')
    world.write('\n				</geometry>')
    world.write('\n				<material>')
    world.write('\n					<script>')
    world.write('\n                            			<uri>file://media/materials/scripts/gazebo.material</uri>')
    world.write('\n                            			<name>Gazebo/Green</name>')
    world.write('\n                        		</script>')
    world.write('\n				</material>')
    world.write('\n			</visual>')
    world.write('\n		</link>')

def create_citrouills(number,pos_X,pos_Y):
    #creation du tronc
    nom_citrouille = ('\n		<link name="citrouille_'+str(number)+'">')
    world.write(nom_citrouille)
    pos_citrouille = ('\n			<pose>'+str(pos_X)+' '+str(pos_Y)+' 1.0  0 0 0</pose>')
    world.write(pos_citrouille)
    world.write('\n			<visual name="visual">')
    world.write('\n				<geometry>')
    world.write('\n					<mesh>')
    world.write('\n						<uri>')
    world.write('\n					<mesh>')
    world.write('							file:///home/dorian/ROS1/cours_ws/src/my_robot/my_robot_gazebo/world/meshes/pumpkin.STL')
    world.write('\n					</mesh>')
    world.write('\n				</geometry>')
    world.write('\n				<material>')
    world.write('\n					<script>')
    world.write('\n                            			<uri>file://media/materials/scripts/gazebo.material</uri>')
    world.write('\n                            			<name>Gazebo/Orange</name>')
    world.write('\n                        		</script>')
    world.write('\n				</material>')
    world.write('\n			</visual>')
    world.write('\n		</link>')

def create_tuteur(number,pos_X,pos_Y):
    #creation du tronc
    nom_tronc = ('\n		<link name="tuteur_'+str(number)+'">')
    world.write(nom_tronc)
    pos_tronc = ('\n			<pose>'+str(pos_X)+' '+str(pos_Y)+' 1.0  0 0 0</pose>')
    world.write(pos_tronc)
    world.write('\n			<visual name="visual">')
    world.write('\n				<geometry>')
    world.write('\n					<cylinder>')
    world.write('\n						<size>0.01 0.09</size>')
    world.write('\n					</cylinder>')
    world.write('\n				</geometry>')
    world.write('\n				<material>')
    world.write('\n					<ambient>0.4 0.3 0.2 1</ambient>')
    world.write('\n					<diffuse>0.3 0.2 0.1 1</diffuse>')
    world.write('\n					<specular>0.1 0.1 0.1 1</specular>')
    world.write('\n					<emissive>0 0 0 0</emissive>')
    world.write('\n					<script>')
    world.write('\n                            			<uri>file://media/materials/scripts/gazebo.material</uri>')
    world.write('\n                            			<name>Gazebo/Red</name>')
    world.write('\n                        		</script>')
    world.write('\n				</material>')
    world.write('\n			</visual>')
    world.write('\n			<collision name="collision">')
    world.write('\n				<geometry>')
    world.write('\n					<box>')
    world.write('\n						<size>0.5 0.5 2.0</size>')
    world.write('\n					</box>')
    world.write('\n				</geometry>')
    world.write('\n			</collision>')
    world.write('\n		</link>')

def fin_obsacle():
    world.write('\n	</model>')

def fin_world():
    world.write('\n    </world>')
    world.write('\n<plugin name="plugins" filename="libplugins.so"/>')
    world.write('\n</sdf>')

world= open("/home/dorian/ROS1/cours_ws/src/my_robot/my_robot_gazebo/world/primary.world", "w")
debut()
ciel_et_soleil(5,10,10)
sol(1000,'Grass')

debut_obsacle('arbres')

nb_arbre = int(input("nombre d'abres : "))
for num in range (0,nb_arbre):
    x = random.randint(-40, 40)
    y = random.randint(-40, 40)
    create_arbre(num,x,y)

fin_obsacle()

debut_obsacle('citrouilles')

nb_citrouilles = int(input("nombre de citrouilles : "))
for num in range (0,nb_citrouilles):
    coeff_x = 1000
    x = random.randint(-2*coeff_x, 2*coeff_x)
    x = x/(coeff_x*10)
    coeff_y = 1000
    y = random.randint(0, 15*coeff_y)
    y = y / coeff_y
    create_citrouills(num,x,y)

nb_tuteurs = int(input("nombre de tuteurs : "))
for num in range (0,nb_tuteurs):
    x = 0.5 * num
    coeff_y = 1000
    y = random.randint(-0.05*coeff_y, 0.05*coeff_y)
    y = 0.4 + y / coeff_y
    create_tuteur(num,x,y)

fin_obsacle()
fin_world()

