<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="my_robot">
    
    <xacro:property name="body_length" value="1.0" />
    <xacro:property name="body_width" value="0.55" />
    <xacro:property name="wheel_width" value="0.15" />
    <xacro:property name="wheel_radius" value="0.15" />
    <!---->
    <xacro:macro name="set_bl_as_parent_link">
        <parent link="base_link" />
    </xacro:macro>

    <!--DEFINITION DE MACRO-->  
    <xacro:macro name="create_wheel" params="position"> 
    
        <link name="${position}_wheel">
                <visual>
                    <xacro:if value="${position=='fl'}">
                        <origin xyz="0.0 ${wheel_width/2} 0.0" rpy="${pi/2} 0.0 0.0" /> 
                    </xacro:if>

                    <xacro:if value="${position=='fr'}">
                        <origin xyz="0.0 ${wheel_width-0.23} 0.0" rpy="${pi/2} 0.0 0.0" />
                    </xacro:if>

                    <xacro:if value="${position=='rl'}">
                        <origin xyz="0.0 ${-wheel_width+0.23} 0.0" rpy="${pi/2} 0.0 0.0" />
                    </xacro:if>

                    <xacro:if value="${position=='rr'}">
                        <origin xyz="0.0 ${-wheel_width/2} 0.0" rpy="${pi/2} 0.0 0.0" />
                    </xacro:if>

                    <geometry>
                        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
                    </geometry>

                </visual>
            </link> 

            <joint name="${position}_wheel_joint" type="continuous">
                <xacro:if value="${position=='fl'}">
                    <origin xyz="${body_length/2-0.1} ${body_width/2} 0.0" /> 
                </xacro:if>

                <xacro:if value="${position=='fr'}">
                    <origin xyz="${body_length/2-0.1} ${-body_width/2} 0.0" /> 
                </xacro:if> 

                <xacro:if value="${position=='rl'}">
                    <origin xyz="${-body_length/2+0.1} ${body_width/2} 0.0" /> 
                </xacro:if>

                <xacro:if value="${position=='rr'}">
                    <origin xyz="${-body_length/2+0.1} ${-body_width/2} 0.0" /> 
                </xacro:if>

                <!--origin xyz="0.4 ${body_width/2} 0.0"-->
                <!--xacro:set_bl_as_parent_link-->  
                <parent link="base_link"/>
                <child link="${position}_wheel"/> 
                <axis xyz="0.0 1.0 0.0" />
            </joint>
    </xacro:macro> 

    <!--SECTION PRINCIPALE-->
    <link name="base_link">
        <visual>
            <geometry>
                <box size="${body_length} ${body_width} 0.25" /> 
            </geometry> 
        </visual>  
    </link> 
    <xacro:create_wheel position="fl"/>
    <xacro:create_wheel position="fr"/>
    <xacro:create_wheel position="rl"/>
    <xacro:create_wheel position="rr"/> 

</robot> 
