<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="my_robot">

    <xacro:property name="wheel_radius" value="0.15"/>
    <xacro:property name="wheel_length" value="0.15"/>
    <xacro:property name="body_length" value="1.0"/>
    <xacro:property name="body_width" value="0.5"/>
    

    <xacro:macro name="set_wheel" params="position">
        <link name="${position}_wheel">
		    <visual>
                <xacro:if value="${position=='hg'}">
                    <origin xyz="0.0 ${wheel_length/2} 0.0" rpy="-1.57 0.0 0.0"/>
                </xacro:if>
                <xacro:if value="${position=='hd'}">
                    <origin xyz="0.0 ${-wheel_length/2} 0.0" rpy="-1.57 0.0 0.0"/>
                </xacro:if>
                <xacro:if value="${position=='bg'}">
                    <origin xyz="0.0 ${wheel_length/2} 0.0" rpy="-1.57 0.0 0.0"/>
                </xacro:if>
                <xacro:if value="${position=='bd'}">
                    <origin xyz="0.0 ${-wheel_length/2} 0.0" rpy="-1.57 0.0 0.0"/>
                </xacro:if>
			    <geometry>
				    <cylinder radius="${wheel_radius}" length="${wheel_length}"/> 
			    </geometry>
		    </visual>
	    </link>	

        <joint name="${position}_wheel_joint" type="continuous">
            <xacro:if value="${position=='hg'}">
                <origin xyz="${body_length/2} ${body_width/2} 0.0" rpy="0.0 0.0 0.0"/>
            </xacro:if>
            <xacro:if value="${position=='hd'}">
                <origin xyz="${body_length/2} ${-body_width/2} 0.0" rpy="0.0 0.0 0.0"/>
            </xacro:if>
            <xacro:if value="${position=='bg'}">
                <origin xyz="${-body_length/2} ${body_width/2} 0.0" rpy="0.0 0.0 0.0"/>
            </xacro:if>
            <xacro:if value="${position=='bd'}">
                <origin xyz="${-body_length/2} ${-body_width/2} 0.0" rpy="0.0 0.0 0.0"/>
            </xacro:if>
            <parent link="base_link"/>
            <child link="${position}_wheel"/>
            <axis xyz="0.0 1 0.0"/>
        </joint>
    </xacro:macro>
    

	<link name="base_link">
		<visual>
			<geometry>
				<box size="${body_length} ${body_width} 0.2"/>
			</geometry>
		</visual>
	</link>	

    <xacro:set_wheel position="hg"/>
    <xacro:set_wheel position="hd"/>
    <xacro:set_wheel position="bg"/>
    <xacro:set_wheel position="bd"/>
</robot>