<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="my_robot">

    <xacro:property name="wheel_radius" value="0.15"/>
    <xacro:property name="wheel_length" value="0.15"/>
    <xacro:property name="wheel_mass" value="2"/>
    <xacro:property name="body_length" value="1.0"/>
    <xacro:property name="body_width" value="0.5"/>
    <xacro:property name="body_height" value="0.5"/>
    <xacro:property name="body_mass" value="10"/>

    <xacro:macro name="set_wheel" params="position">
        <link name="${position}_wheel">
		    <visual>
                <xacro:if value="${position=='hg'}">
                    <origin xyz="0.0 ${wheel_length/2} 0.0" rpy="-1.57 0.0 0.0"/>
                </xacro:if>
                <xacro:if value="${position=='hd'}">
                    <origin xyz="0.0 ${-wheel_length/2} 0.0" rpy="-1.57 0.0 0.0"/>
                </xacro:if>
                <xacro:if value="${position=='bg'}">
                    <origin xyz="0.0 ${wheel_length/2} 0.0" rpy="-1.57 0.0 0.0"/>
                </xacro:if>
                <xacro:if value="${position=='bd'}">
                    <origin xyz="0.0 ${-wheel_length/2} 0.0" rpy="-1.57 0.0 0.0"/>
                </xacro:if>
			    <geometry>
				    <cylinder radius="${wheel_radius}" length="${wheel_length}"/> 
			    </geometry>
		    </visual>

            <collision>
                <xacro:if value="${position=='hg'}">
                    <origin xyz="0.0 ${wheel_length/2} 0.0" rpy="-1.57 0.0 0.0"/>
                </xacro:if>
                <xacro:if value="${position=='hd'}">
                    <origin xyz="0.0 ${-wheel_length/2} 0.0" rpy="-1.57 0.0 0.0"/>
                </xacro:if>
                <xacro:if value="${position=='bg'}">
                    <origin xyz="0.0 ${wheel_length/2} 0.0" rpy="-1.57 0.0 0.0"/>
                </xacro:if>
                <xacro:if value="${position=='bd'}">
                    <origin xyz="0.0 ${-wheel_length/2} 0.0" rpy="-1.57 0.0 0.0"/>
                </xacro:if>
			    <geometry>
				    <cylinder radius="${wheel_radius}" length="${wheel_length}"/> 
			    </geometry>
		    </collision>
            <xacro:cylinder_inertial mass="${wheel_mass}" r="${wheel_radius}" h="${wheel_length}"/>
	    </link>	

        <joint name="${position}_wheel_joint" type="continuous">
            <xacro:if value="${position=='hg'}">
                <origin xyz="${body_length/2} ${body_width/2} 0.0" rpy="0.0 0.0 0.0"/>
            </xacro:if>
            <xacro:if value="${position=='hd'}">
                <origin xyz="${body_length/2} ${-body_width/2} 0.0" rpy="0.0 0.0 0.0"/>
            </xacro:if>
            <xacro:if value="${position=='bg'}">
                <origin xyz="${-body_length/2} ${body_width/2} 0.0" rpy="0.0 0.0 0.0"/>
            </xacro:if>
            <xacro:if value="${position=='bd'}">
                <origin xyz="${-body_length/2} ${-body_width/2} 0.0" rpy="0.0 0.0 0.0"/>
            </xacro:if>
            <parent link="base_link"/>
            <child link="${position}_wheel"/>
            <axis xyz="0.0 1 0.0"/>
        </joint>
    </xacro:macro>
    
        <!-- MACROS -->
    <xacro:macro name="box_inertial" params="mass l w h">
        <inertial>
                <mass value="${mass}" />
                <inertia ixx="${mass/3*(w*w + h*h)}" ixy="${mass/4*l*w}" ixz="${mass/4*l*h}"
                     iyy="${mass/3*(l*l + h*h)}" iyz="${mass/4*w*h}"
                     izz="${mass/3*(l*l + w*w)}" />
        </inertial>
    </xacro:macro>
    <xacro:macro name="cylinder_inertial" params="mass r h">
        <inertial>
                <mass value="${mass}" />
                <inertia ixx="${mass/12*(3*r*r + h*h)}" ixy="0.0" ixz="0.0"
                     iyy="${mass/12*(3*r*r + h*h)}" iyz="0.0"
                     izz="${mass/2*(r*r)}" />
        </inertial>
    </xacro:macro>
    <xacro:macro name="spherus_inertial" params="mass r">
        <inertial>
                <mass value="${mass}" />
                <inertia ixx="${mass/5*2*(r*r)}" ixy="0.0" ixz="0.0"
                     iyy="${mass/5*2*(r*r)}" iyz="0.0"
                     izz="${mass/5*2*(r*r)}" />
        </inertial>
    </xacro:macro>
    <!-- ____________________________________________ -->

	<link name="base_link">
		<visual>
			<geometry>
				<box size="${body_length} ${body_width} 0.2"/>
			</geometry>
		</visual>
        <xacro:box_inertial mass="${body_mass}" l="${body_length}" w="${body_width}" h="${body_height}"/>
	</link>	

    <xacro:set_wheel position="hg"/>
    <xacro:set_wheel position="hd"/>
    <xacro:set_wheel position="bg"/>
    <xacro:set_wheel position="bd"/>
</robot>

